import Head from "next/head";
import Image from "next/image";
import Banner from "../components/banner";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handleOnBannerButtonClick = () => {
    console.log("hello to Banner from Home Component");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          handleButtonClick={handleOnBannerButtonClick}
          buttonText="View stores nearby"
        />
        <div className={styles.heroImage}>
          {" "}
          <Image src="/static/hero-image.png" width={700} height={400} />{" "}
        </div>
      </main>
    </div>
  );
}
